### ISSUE TITLE
Duplicated key in localStorage

### ISSUE THREAD

**Issue by tofikabdullayev** [CatChen/browser-id#282]
Hi. I'm trying to use this package in my Nuxt project.

importing and generating id like this: 

`import * as browserId from "browser-id";
    const id = browserId();
`

Result is folowing: 
![ids](https://user-images.githubusercontent.com/10906783/150782410-fbfa031c-2eb2-47c7-933b-09ef24cada21.JPG)

**Comment by CatChen** [comment]
@tofikabdullayev That's the expected behavior. `browser_id = 1` means the schema version of `browser_id` is `1`. `browser_id:1 = "..."` is the actual value. There could be a `browser_id:2` if there's a breaking schema change in the future. There's no plan to upgrade the schema version, but that's the implementation details in the underlying [versioned-storage](https://www.npmjs.com/package/versioned-storage) behavior.
